SELECT I.ITEM_ID,I.ITEM_NAME,I.RARITY 
FROM ITEM_INFO I
WHERE I.ITEM_ID IN (SELECT T.ITEM_ID FROM ITEM_TREE T
JOIN ITEM_INFO P ON T.PARENT_ITEM_ID=P.ITEM_ID
WHERE P.RARITY='RARE'
                   )
                   ORDER BY I.ITEM_ID DESC