SELECT
YEAR(A.DIFFERENTIATION_DATE) YEAR,
(B.MAX_SIZE-A.SIZE_OF_COLONY) YEAR_DEV,
ID
FROM ECOLI_DATA A
JOIN
(SELECT MAX(SIZE_OF_COLONY) MAX_SIZE,
YEAR(DIFFERENTIATION_DATE) DATE
FROM ECOLI_DATA
GROUP BY DATE) B
ON YEAR(A.DIFFERENTIATION_DATE)=B.DATE
ORDER BY
YEAR,YEAR_DEV