SELECT 
    HG.SCORE,
    HE.EMP_NO,
    HE.EMP_NAME,
    HE.POSITION,
    HE.EMAIL 
FROM HR_EMPLOYEES HE
JOIN 
    (SELECT 
        SUM(SCORE) AS SCORE,
        EMP_NO 
     FROM HR_GRADE
     GROUP BY EMP_NO) HG
ON HE.EMP_NO = HG.EMP_NO
WHERE HG.SCORE = (
    SELECT MAX(SCORE)
    FROM (
        SELECT SUM(SCORE) AS SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) AS MAX_SCORE
)

